Batch04/CRBS_Project/Controllers/BookingInfoModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CRBS_Project.Models;
using CRBS_Project.Repository;

namespace CRBS_Project.Controllers
{
    public class BookingInfoModelsController : Controller
    {
        private CRBSystemContext db = new CRBSystemContext();

        // GET: BookingInfoModels
        public ActionResult Index()
        {
            var bookingInfoModels = db.BookingInfoModels.Include(b => b.ConferenceRoomInfoModels);
            return View(bookingInfoModels.ToList());
        }

        // GET: BookingInfoModels/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingInfoModels bookingInfoModels = db.BookingInfoModels.Find(id);
            if (bookingInfoModels == null)
            {
                return HttpNotFound();
            }
            return View(bookingInfoModels);
        }

        // GET: BookingInfoModels/Create
        public ActionResult Create()
        {
            ViewBag.PropertyId = new SelectList(db.ConferenceRoomInfoModels, "PropertyId", "PropertyName");
            return View();
        }

        // POST: BookingInfoModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BookingId,PropertyId,UserId,BookingDate,FromTime,ToTime,BookingStatus,StatusName")] BookingInfoModels bookingInfoModels)
        {
            if (ModelState.IsValid)
            {
                db.BookingInfoModels.Add(bookingInfoModels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PropertyId = new SelectList(db.ConferenceRoomInfoModels, "PropertyId", "PropertyName", bookingInfoModels.PropertyId);
            return View(bookingInfoModels);
        }

        // GET: BookingInfoModels/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingInfoModels bookingInfoModels = db.BookingInfoModels.Find(id);
            if (bookingInfoModels == null)
            {
                return HttpNotFound();
            }
            ViewBag.PropertyId = new SelectList(db.ConferenceRoomInfoModels, "PropertyId", "PropertyName", bookingInfoModels.PropertyId);
            return View(bookingInfoModels);
        }

        // POST: BookingInfoModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BookingId,PropertyId,UserId,BookingDate,FromTime,ToTime,BookingStatus,StatusName")] BookingInfoModels bookingInfoModels)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bookingInfoModels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PropertyId = new SelectList(db.ConferenceRoomInfoModels, "PropertyId", "PropertyName", bookingInfoModels.PropertyId);
            return View(bookingInfoModels);
        }

        // GET: BookingInfoModels/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BookingInfoModels bookingInfoModels = db.BookingInfoModels.Find(id);
            if (bookingInfoModels == null)
            {
                return HttpNotFound();
            }
            return View(bookingInfoModels);
        }

        // POST: BookingInfoModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            BookingInfoModels bookingInfoModels = db.BookingInfoModels.Find(id);
            db.BookingInfoModels.Remove(bookingInfoModels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Batch04/CRBS_Project/Controllers/ConferenceRoomInfoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CRBS_Project.Models;
using CRBS_Project.Repository;

namespace CRBS_Project.Controllers
{
    public class ConferenceRoomInfoController : Controller
    {
        private CRBSystemContext db = new CRBSystemContext();

        // GET: ConferenceRoomInfo
        public ActionResult Index()
        {
            var conferenceRoomInfoModels = db.ConferenceRoomInfoModels.Include(c => c.PropertyTypeInfo).Include(c => c.RoomType);
            return View(conferenceRoomInfoModels.ToList());
        }

        // GET: ConferenceRoomInfo/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ConferenceRoomInfoModels conferenceRoomInfoModels = db.ConferenceRoomInfoModels.Find(id);
            if (conferenceRoomInfoModels == null)
            {
                return HttpNotFound();
            }
            return View(conferenceRoomInfoModels);
        }

        // GET: ConferenceRoomInfo/Create
        public ActionResult Create()
        {
            ViewBag.PropertyPurposeId = new SelectList(db.PropertyTypeInfo, "PropertyPurposeId", "PropertyPurposeName");
            ViewBag.RoomTypeId = new SelectList(db.RoomType, "RoomTypeId", "RoomTypeName");
            return View();
        }

        // POST: ConferenceRoomInfo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PropertyId,PropertyName,PersonCapacity,PropertyPurposeId,RoomTypeId,FairAmount")] ConferenceRoomInfoModels conferenceRoomInfoModels)
        {
            if (ModelState.IsValid)
            {
                db.ConferenceRoomInfoModels.Add(conferenceRoomInfoModels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PropertyPurposeId = new SelectList(db.PropertyTypeInfo, "PropertyPurposeId", "PropertyPurposeName", conferenceRoomInfoModels.PropertyPurposeId);
            ViewBag.RoomTypeId = new SelectList(db.RoomType, "RoomTypeId", "RoomTypeName", conferenceRoomInfoModels.RoomTypeId);
            return View(conferenceRoomInfoModels);
        }

        // GET: ConferenceRoomInfo/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ConferenceRoomInfoModels conferenceRoomInfoModels = db.ConferenceRoomInfoModels.Find(id);
            if (conferenceRoomInfoModels == null)
            {
                return HttpNotFound();
            }
            ViewBag.PropertyPurposeId = new SelectList(db.PropertyTypeInfo, "PropertyPurposeId", "PropertyPurposeName", conferenceRoomInfoModels.PropertyPurposeId);
            ViewBag.RoomTypeId = new SelectList(db.RoomType, "RoomTypeId", "RoomTypeName", conferenceRoomInfoModels.RoomTypeId);
            return View(conferenceRoomInfoModels);
        }

        // POST: ConferenceRoomInfo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PropertyId,PropertyName,PersonCapacity,PropertyPurposeId,RoomTypeId,FairAmount")] ConferenceRoomInfoModels conferenceRoomInfoModels)
        {
            if (ModelState.IsValid)
            {
                db.Entry(conferenceRoomInfoModels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PropertyPurposeId = new SelectList(db.PropertyTypeInfo, "PropertyPurposeId", "PropertyPurposeName", conferenceRoomInfoModels.PropertyPurposeId);
            ViewBag.RoomTypeId = new SelectList(db.RoomType, "RoomTypeId", "RoomTypeName", conferenceRoomInfoModels.RoomTypeId);
            return View(conferenceRoomInfoModels);
        }

        // GET: ConferenceRoomInfo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ConferenceRoomInfoModels conferenceRoomInfoModels = db.ConferenceRoomInfoModels.Find(id);
            if (conferenceRoomInfoModels == null)
            {
                return HttpNotFound();
            }
            return View(conferenceRoomInfoModels);
        }

        // POST: ConferenceRoomInfo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ConferenceRoomInfoModels conferenceRoomInfoModels = db.ConferenceRoomInfoModels.Find(id);
            db.ConferenceRoomInfoModels.Remove(conferenceRoomInfoModels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Batch04/CRBS_Project/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CRBS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("|CRBS System|", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Dashboard", "Index", "ConferenceRoomInfo")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />*@
        @*<footer>
                <p>&copy; @DateTime.Now.Year - Static Group Application</p>
            </footer>*@

        <footer class="footer" style="background-color:#222; margin-left: -113px;">
            <div class="container">
                <div class="col-md-12">

                    <p style="color: #fff; text-align: right; margin-top: 4px; margin-bottom: 4px;">&copy; @DateTime.Now.Year - Static Group Application</p>
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
    $('.dropdown').hover(function () {
        $('.dropdown-toggle', this).trigger('click');
    });
    </script>

</body>
</html>

Batch04/CRBS_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CRBS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("|CRBS System|", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Conference Room Info", "Index", "ConferenceRoomInfo")</li>
                    <li>@Html.ActionLink("Booking Info", "Index", "BookingInfoModels")</li>
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    @*<li>@Html.ActionLink("Booking Confirm", "Index", "Home")</li>
                    <li>@Html.ActionLink("Booking Confirm Cancel", "Index", "Home")</li>
                    <li>@Html.ActionLink("Payment System", "Index", "Home")</li>*@

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Setup<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Booking Confirm", "Index", "Home")</li>
                            <li>@Html.ActionLink("Booking Confirm Cancel", "Index", "Home")</li>
                            <li>@Html.ActionLink("Payment System", "Index", "Home")</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />*@
        @*<footer>
            <p>&copy; @DateTime.Now.Year - Static Group Application</p>
        </footer>*@

        <footer class="footer" style="background-color:#222; margin-left: -113px;">
            <div class="container">
                <div class="col-md-12">

                    <p style="color: #fff; text-align: right; margin-top: 4px; margin-bottom: 4px;">&copy; @DateTime.Now.Year - Static Group Application</p>
                </div>
            </div>
        </footer>
    </div>
    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script>
    $('.dropdown').hover(function () {
        $('.dropdown-toggle', this).trigger('click');
    });
    </script>

</body>
</html>